### ISSUE TITLE
Missing Library in qTox-8c34fa8f7d34e6555533f392925164b47da12d8c-x86_64.AppImage

### ISSUE THREAD

**Issue by mj162** [qTox/qTox-nightly-releases#1]
Hi, thank you for your work.

qTox-8c34fa8f7d34e6555533f392925164b47da12d8c-x86_64.AppImage fails to run on:-

- HP ThinPro 7.1 (Ubuntu 16.04 LTS derivative)
- HP ThinPro 7.2 (Ubuntu 18.04 LTS derivative)

Missing Library: **libfribidi.so.0**

**Comment by sudden6** [comment]
Moving to our main issue tracker: https://github.com/qTox/qTox/issues/6337
